# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    name: Build
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: checking the dir
        uses: pwd
          
      - name: hadolint linting
        run: docker run --rm -i -v /.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint:latest < Dockerfile

          
